language: python

os:
    - linux
    - osx

services:
    - docker

before_install:
    - docker login -u utsav030 -p utsavmiet2580
    - docker pull utsav030/example
    - docker run utsav030/example

